openapi: 3.0.3
info:
  title: Elevate Scheduler
  description: >-
    This is a Job Scheduling Service based on the BullMQ library. With the power
    of BullMQ, this service provides a robust and scalable solution for handling
    job queues and scheduling tasks. The Job Scheduling Service enables them to
    streamline their workflow by automating recurring tasks, background
    processing, and asynchronous job execution. It empowers administrators, and
    developers to define and manage complex job scheduling requirements with
    ease.
  termsOfService: ''
  contact:
    email: tech-infra@shikshalokam.org
  license:
    name: MIT License
    url: ttps://github.com/ELEVATE-Project/scheduler/blob/master/LICENSE
  version: '1'
externalDocs:
  description: ''
  url: ''
servers:
  - url: http://127.0.0.1:4000
    description: Localhost
tags:
  - name: Default
    description: ''
    externalDocs:
      description: ''
      url: ''
paths:
  /scheduler/jobs/create:
    post:
      summary: Create repeatable jobs
      description: >-
        The Scheduler Service using BullMQ allows you to add jobs to a queue
        with different scheduling options. It supports three types of jobs:
        delayed jobs, repeatable jobs with a cron pattern, and repeatable jobs
        with an interval. Accepts a JSON request body with specific parameters.
      operationId: /scheduler/jobs/create
      tags:
        - Default
      parameters: []
      requestBody:
        description: Job details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create-schema'
            examples:
              Create delayed jobs:
                value:
                  jobName: emailCronJobBeforeOneHour
                  email:
                    - nevil@tunerlabs.com
                  request:
                    url: >-
                      http://mentoring:3000/mentoring/v1/notifications/emailCronJobBeforeOneHour
                    method: get
                    header:
                      internal_access_token: internal_access_token
                  jobOptions:
                    jobId: emailCronJobBeforeOneHour
                    delay: 500000
                    removeOnComplete: true
                    removeOnFail: false
                    attempts: 1
              Create repeatable jobs with interval:
                value:
                  jobName: emailCronJobBeforeOneHour
                  email:
                    - nevil@tunerlabs.com
                  request:
                    url: >-
                      http://mentoring:3000/mentoring/v1/notifications/emailCronJobBeforeOneHour
                    method: get
                    header:
                      internal_access_token: internal_access_token
                  jobOptions:
                    jobId: emailCronJobBeforeOneHour
                    repeat:
                      every: 100
                      limit: 250
                    removeOnComplete: 50
                    removeOnFail: 200
                    attempts: 3
              Create repeatable jobs with cron:
                value:
                  jobName: emailCronJobBeforeOneHour
                  email:
                    - nevil@tunerlabs.com
                  request:
                    url: >-
                      http://mentoring:3000/mentoring/v1/notifications/emailCronJobBeforeOneHour
                    method: get
                    header:
                      internal_access_token: internal_access_token
                  jobOptions:
                    jobId: emailCronJobBeforeOneHour
                    repeat:
                      pattern: 15 3 * * *
                    removeOnComplete: 100
                    removeOnFail: 200
                    attempts: 3
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/create-response-schema'
              examples:
                ' Delayed job response':
                  value:
                    success: true
                    responseCode: 200
                    message: Job queued successfully
                    result:
                      name: emailCronJobBeforeOneHour
                      data:
                        email:
                          - nevil@tunerlabs.com
                        request:
                          url: >-
                            http://mentoring:3000/mentoring/v1/notifications/emailCronJobBeforeOneHour
                          method: get
                          header:
                            internal_access_token: internal_access_token
                      opts:
                        attempts: 1
                        delay: 500000
                        jobId: emailCronJobBeforeOneHour
                        removeOnComplete: true
                        removeOnFail: false
                      id: emailCronJobBeforeOneHour
                      progress: 0
                      returnvalue: null
                      stacktrace: null
                      attemptsMade: 0
                      delay: 500000
                      timestamp: 1684836046766
                    meta:
                      correlation: cf4ff717-258a-477e-acb3-4f2bbaa969b9
                ' Repetable job response(interval)':
                  value:
                    success: true
                    responseCode: 200
                    message: Job queued successfully
                    result:
                      name: emailCronJobBeforeOneHour
                      data:
                        email:
                          - nevil@tunerlabs.com
                        request:
                          url: >-
                            http://mentoring:3000/mentoring/v1/notifications/emailCronJobBeforeOneHour
                          method: get
                          header:
                            internal_access_token: internal_access_token
                      opts:
                        attempts: 3
                        delay: 28
                        jobId: repeat:21726a02ac95e12429d76fa2bc4be622:1684856243000
                        repeat:
                          every: 100
                          limit: 250
                          jobId: emailCronJobBeforeOneHour
                          count: 1
                        removeOnComplete: 50
                        removeOnFail: 200
                        timestamp: 1684856242972
                        prevMillis: 1684856243000
                      id: repeat:21726a02ac95e12429d76fa2bc4be622:1684856243000
                      progress: 0
                      returnvalue: null
                      stacktrace: null
                      attemptsMade: 0
                      delay: 28
                      repeatJobKey: >-
                        emailCronJobBeforeOneHour:emailCronJobBeforeOneHour:::100
                      timestamp: 1684856242972
                    meta:
                      correlation: 1b40e9b7-91ce-40ae-80ba-735e5b34d46e
                ' Delayed job response(cron)':
                  value:
                    success: true
                    responseCode: 200
                    message: Job queued successfully
                    result:
                      name: emailCronJobBeforeOneHour
                      data:
                        email:
                          - nevil@tunerlabs.com
                        request:
                          url: >-
                            http://mentoring:3000/mentoring/v1/notifications/emailCronJobBeforeOneHour
                          method: get
                          header:
                            internal_access_token: internal_access_token
                      opts:
                        attempts: 3
                        delay: 41918808
                        jobId: repeat:f17f9ebd8e9a8b916c55a57a567aadaa:1684898100000
                        repeat:
                          pattern: 15 3 * * *
                          jobId: emailCronJobBeforeOneHour
                          count: 1
                        removeOnComplete: 100
                        removeOnFail: 200
                        timestamp: 1684856181192
                        prevMillis: 1684898100000
                      id: repeat:f17f9ebd8e9a8b916c55a57a567aadaa:1684898100000
                      progress: 0
                      returnvalue: null
                      stacktrace: null
                      attemptsMade: 0
                      delay: 41918808
                      repeatJobKey: >-
                        emailCronJobBeforeOneHour:emailCronJobBeforeOneHour:::15
                        3 * * *
                      timestamp: 1684856181192
                    meta:
                      correlation: 986c2de2-93a8-4f13-a13f-59501c58d287
          headers: {}
          description: Success response
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/create-response-failure-schema'
              examples:
                Error response:
                  value:
                    success: false
                    message: A job already exists with the same ID
                    error: []
                    meta:
                      correlation: 1f76fd28-a861-4b2c-86d6-be8c4c70de0f
          description: Failure Response
      deprecated: false
  /scheduler/jobs/remove:
    post:
      summary: To remove a single job
      description: >-
        Remove a single job by providing its ID. Accepts a JSON request body
        with the jobId parameter.
      operationId: /scheduler/jobs/remove
      tags:
        - Default
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/remove-job-schema'
            examples:
              Request body:
                value:
                  jobId: emailCronJobBeforeOneHour
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/remove-job-response-success-schema'
              examples:
                Response:
                  value:
                    success: true
                    responseCode: 200
                    message: Job successfully removed
                    result: true
                    meta:
                      correlation: 73c06d73-8fb1-487f-b073-992233231bd6
          description: Success response
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/remove-job-response-failure-schema'
              examples:
                Failure response:
                  value:
                    success: false
                    message: No job found with the specified ID
                    error: []
                    meta:
                      correlation: e08c248a-fbee-459f-b41a-97018663a51d
          description: Response when job not found
  /scheduler/jobs/purge:
    post:
      summary: Purge jobs/queue
      description: >-
        Purge jobs/queue using different methods (clean, drain, obliterate).
        Accepts a JSON request body with the method and options parameters.

        Note: "options" parameter is only needed for the clean method.
      operationId: /scheduler/jobs/purge
      tags:
        - Default
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/purge-schema'
            examples:
              Clean method:
                value:
                  method: clean
                  options:
                    gracePeriod: 60
                    limit: 0
                    jobStatus: failed
              Drain method:
                value:
                  method: drain
              Obliterate method:
                value:
                  method: obliterate
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/purge-success-response-schema'
              examples:
                Clean method:
                  value:
                    success: true
                    responseCode: 200
                    message: Jobs cleaned successfully
                    result: {}
                    meta:
                      correlation: b55ee699-981b-48b8-84f0-93a118daaaa8
                Drain method:
                  value:
                    success: true
                    responseCode: 200
                    message: Queue drained successfully
                    result: {}
                    meta:
                      correlation: 495edbc7-9c80-4d32-b9db-6b0b57f52ba5
                Obliterate method:
                  value:
                    success: true
                    responseCode: 200
                    message: Queue obliterated successfully
                    result: {}
                    meta:
                      correlation: fe7d4a8f-76f0-436a-9f9b-e118a89c346f
          description: Success Response
  /scheduler/jobs/list:
    get:
      description: Retrieve a list of jobs.
      operationId: /scheduler/jobs/list
      tags:
        - Default
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/list-response-schema'
              examples:
                Response:
                  value:
                    success: true
                    responseCode: 200
                    message: Job list successfully retrieved
                    result:
                      - name: emailCronJobBeforeOneHour
                        opts:
                          attempts: 3
                          delay: 62343133
                          prevMillis: 1684898100000
                          timestamp: 1684835756867
                          removeOnFail: 200
                          removeOnComplete: 100
                          jobId: >-
                            repeat:f17f9ebd8e9a8b916c55a57a567aadaa:1684898100000
                          repeat:
                            jobId: emailCronJobBeforeOneHour
                            pattern: 15 3 * * *
                            count: 1
                        id: repeat:f17f9ebd8e9a8b916c55a57a567aadaa:1684898100000
                        progress: 0
                        returnvalue: 'null'
                        stacktrace: []
                        attemptsMade: 0
                        delay: 62343133
                        repeatJobKey: >-
                          emailCronJobBeforeOneHour:emailCronJobBeforeOneHour:::15
                          3 * * *
                        timestamp: 1684835756867
                    meta:
                      correlation: 8dec3a0b-1622-4d11-9071-4434c126b598
          description: Success response
      summary: Get list of jobs
components:
  schemas:
    create-schema:
      type: object
      properties:
        jobName:
          type: string
          description: Name of the job to be executed
        email:
          type: array
          items:
            type: string
          description: ' Email addresses associated with the job to report job failure'
        request:
          type: object
          properties:
            url:
              type: string
              description: URL for the HTTP request
            method:
              type: string
              enum:
                - get, post, put, delete
              description: HTTP method for the request
            header:
              type: object
              properties:
                internal_access_token:
                  type: string
              required:
                - internal_access_token
              description: Headers for the request
          required:
            - url
            - method
            - header
          description: Details about the HTTP request to be made when the job is processed
        jobOptions:
          oneOf:
            - $ref: '#/components/schemas/delay'
            - $ref: '#/components/schemas/repeat'
      required:
        - jobName
        - email
        - request
        - jobOptions
      description: Additional options for the job
    create-response-schema:
      type: object
      properties:
        success:
          type: boolean
        responseCode:
          type: number
        message:
          type: string
        result:
          type: object
          properties:
            name:
              type: string
            data:
              type: object
              properties:
                email:
                  type: array
                  items:
                    type: string
                request:
                  type: object
                  properties:
                    url:
                      type: string
                    method:
                      type: string
                    header:
                      type: object
                      properties:
                        internal_access_token:
                          type: string
            opts:
              type: object
              properties:
                attempts:
                  type: number
                delay:
                  type: number
                jobId:
                  type: string
                removeOnComplete:
                  type: boolean
                removeOnFail:
                  type: boolean
            id:
              type: string
            progress:
              type: number
            returnvalue:
              type: string
            stacktrace:
              type: string
            attemptsMade:
              type: number
            delay:
              type: number
            timestamp:
              type: number
        meta:
          type: object
          properties:
            correlation:
              type: string
    remove-job-schema:
      type: object
      properties:
        jobId:
          type: string
      required:
        - jobId
    remove-job-response-failure-schema:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        error:
          type: array
          items:
            type: string
        meta:
          type: object
          properties:
            correlation:
              type: string
          required:
            - correlation
      required:
        - meta
        - success
        - message
        - error
    remove-job-response-success-schema:
      type: object
      properties:
        success:
          type: boolean
        responseCode:
          type: number
        message:
          type: string
        result:
          type: boolean
        meta:
          type: object
          properties:
            correlation:
              type: string
          required:
            - correlation
      required:
        - success
        - responseCode
        - message
        - result
        - meta
    purge-success-response-schema:
      type: object
      properties:
        success:
          type: boolean
        responseCode:
          type: number
        message:
          type: string
        result:
          type: object
        meta:
          type: object
          properties:
            correlation:
              type: string
      description: Request Response
    purge-schema:
      type: object
      properties:
        method:
          type: string
          enum:
            - clean, drain, obliterate
          description: BullMQ method for purging jobs
        options:
          oneOf:
            - $ref: '#/components/schemas/CleanOptions'
            - $ref: '#/components/schemas/DrainOrObliterateOptions'
          description: Options specific to the selected purging method
      required:
        - method
    CleanOptions:
      type: object
      properties:
        gracePeriod:
          type: integer
          description: Time in milliseconds for grace period
        limit:
          type: integer
          description: Maximum number of jobs to remove, 0 means all
        jobStatus:
          type: string
          enum:
            - completed
            - failed
            - active
            - delayed
            - waiting
          description: Filter jobs based on their status
      required:
        - gracePeriod
        - limit
        - jobStatus
    DrainOrObliterateOptions:
      type: object
      description: No additional options required for the 'drain' or 'obliterate' method
    create-response-failure-schema:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        error:
          type: array
          items:
            type: string
        meta:
          type: object
          properties:
            correlation:
              type: string
    list-response-schema:
      type: object
      properties:
        success:
          type: boolean
        responseCode:
          type: number
        message:
          type: string
        result:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              opts:
                type: object
                properties:
                  attempts:
                    type: number
                  delay:
                    type: number
                  prevMillis:
                    type: number
                  timestamp:
                    type: number
                  removeOnFail:
                    type: number
                  removeOnComplete:
                    type: number
                  jobId:
                    type: string
                  repeat:
                    type: object
                    properties:
                      jobId:
                        type: string
                      pattern:
                        type: string
                      count:
                        type: number
              id:
                type: string
              progress:
                type: number
              returnvalue:
                type: string
              stacktrace:
                type: array
                items:
                  type: string
              attemptsMade:
                type: number
              delay:
                type: number
              repeatJobKey:
                type: string
              timestamp:
                type: number
        meta:
          type: object
          properties:
            correlation:
              type: string
    IntervalRepeat:
      type: object
      properties:
        every:
          type: integer
          description: Interval duration in milliseconds between each execution of the job
        limit:
          type: integer
          description: Maximum number of times the job should be repeated (optional)
      required:
        - every
    CronRepeat:
      type: object
      properties:
        pattern:
          type: string
          description: Cron pattern specifying the schedule for job execution
      required:
        - pattern
    repeat:
      $schema: http://json-schema.org/draft-04/schema#
      type: object
      properties:
        jobId:
          type: string
          description: Unique identifier for the job
        repeat:
          oneOf:
            - $ref: '#/components/schemas/IntervalRepeat'
            - $ref: '#/components/schemas/CronRepeat'
          description: Additional options for the job
        removeOnComplete:
          type: number
          description: Number of jobs to keep after completion
        removeOnFail:
          type: number
          description: Number of jobs to keep after failure
        attempts:
          type: number
          description: Number of times the job can be retried if it fails
      required:
        - jobId
        - repeat
    delay:
      $schema: http://json-schema.org/draft-04/schema#
      type: object
      properties:
        jobId:
          type: string
          description: Unique identifier for the job
        delay:
          type: number
          description: Delay in milliseconds before the job is processed
        removeOnComplete:
          type: boolean
          description: >-
            Whether the job should be removed from the queue when completed
            successfully
        removeOnFail:
          type: boolean
          description: Whether the job should be removed from the queue if it fails
        attempts:
          type: number
          description: Number of times the job can be retried if it fails
      required:
        - delay
        - jobId
  securitySchemes: {}
